### ISSUE TITLE
Monitor screen has ability to choose from list of actual device monitor interfaces

### ISSUE THREAD

**Issue by rsauvehoover** [MockCode/MockCode#11]
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"psd":"2018-02-25T00:00:00-07:00","ped":"2018-03-28T00:00:00-06:00"})

**Comment by hughboi** [comment]
Updated the name of this issue to reflect the change in requirements as discussed in a meeting. The patient face screen will now give the user an option to select what the interface looks like from a list of actual monitor device presets seen in the real world!

**Comment by rsauvehoover** [comment]
Not necessary for patient face to have this option

**Comment by hughboi** [comment]
Addressed by merged pull request #89, and can now be closed.
