### ISSUE TITLE
Select Device Interface

### ISSUE THREAD

**Issue by kuzi117** [MockCode/MockCode#14]
Choose which interface the device will serve. It can be either a Command, Monitor, or Patient Face.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"psd":"2018-02-14T00:00:00-07:00","ped":"2018-03-15T01:00:00-06:00"})

**Comment by coltonbegert** [comment]
This addresses Use Case 3
