### ISSUE TITLE
Current Nearby Interfaces

### ISSUE THREAD

**Issue by kuzi117** [MockCode/MockCode#15]
A list is shown of the different device interfaces. An indicator shows whether a certain interface is currently attended by a nearby connected device, or the current device.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"psd":"2018-02-02T00:00:00-07:00","ped":"2018-02-26T01:00:00-07:00"})

**Comment by coltonbegert** [comment]
This addresses Use Case 4

**Comment by coltonbegert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UC4](https://trello.com/c/2f7anIez/11-uc4)
