### ISSUE TITLE
Adjusting Heart Rate

### ISSUE THREAD

**Issue by kuzi117** [MockCode/MockCode#16]
Adjusting the heart-rate displayed on the monitor from the control.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"psd":"2018-02-02T00:00:00-07:00","ped":"2018-02-26T01:00:00-07:00"})

**Comment by coltonbegert** [comment]
This addresses Use Case 4

**Comment by coltonbegert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UC5](https://trello.com/c/FALqoAjv/12-uc5)

**Comment by hughboi** [comment]
This feature has been completed by pull request #62, and thus the issue will be closed. Note that although the use case says that the monitor will react according to the changes sent by this implemented feature, we do not have waveforms to show yet. However, the core functionality exists, and thus the rest of the work will be tracked by issue #25.
