### ISSUE TITLE
Adjusting Blood Pressure

### ISSUE THREAD

**Issue by kuzi117** [MockCode/MockCode#18]
As an instructor I want to be able to change simulation parameters: heart rate, O2 saturation, CO2 saturation, and blood pressure.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"psd":"2018-02-02T00:00:00-07:00","ped":"2018-02-26T01:00:00-07:00"})

**Comment by coltonbegert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UC6](https://trello.com/c/TPHQmdsp/13-uc6)

**Comment by hughboi** [comment]
This feature has been completed by pull request #62, and thus the issue will be closed. Note that although the use case says that the monitor will react according to the changes sent by this implemented feature, we do not have waveforms to show yet. However, the core functionality exists, and thus the rest of the work will be tracked by issue #25.

**Comment by rsauvehoover** [comment]
START_DATE_STRING: "#### 🗓 Start Date:2018-02-01"
DUE_DATE_STRING: "#### 🗓 Expected Date:2018-02-26"
LABEL_STRING: "#### 🏷 Label:Adjusting Blood Pressure"
PROGRESS_STRING: "#### 📈 Progress (0-1):1"
