### ISSUE TITLE
Toggling Breathing Status

### ISSUE THREAD

**Issue by kuzi117** [MockCode/MockCode#19]
Switching between patient breathing and non-breathing.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"psd":"2018-03-21T12:00:00-06:00","ped":"2018-04-05T01:00:00-06:00"})

**Comment by hughboi** [comment]
I'm pretty sure Dr. Corser said earlier that we didn't need this use case at all, and he wasn't sure why we had created it.

**Comment by hughboi** [comment]
Closing as this feature was not actually requested, or wanted when asking the customer.
