### ISSUE TITLE
Adjust Heartbeat Wave Form

### ISSUE THREAD

**Issue by kuzi117** [MockCode/MockCode#21]
Switches between a selection of different heartbeat waveforms.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"psd":"2018-02-26T09:00:00-07:00","ped":"2018-03-15T01:00:00-06:00"})

**Comment by hughboi** [comment]
This issue will be closed by the merging of PR #73, and I will add a new issue to update the UI for this use case in sprint 4.
