### ISSUE TITLE
Observe/Hear Simulation Parameters

### ISSUE THREAD

**Issue by kuzi117** [MockCode/MockCode#25]
Participants should be able to observe changes made by the command interface to O<sub>2</sub> saturation, CO<sub>2</sub> saturation, blood pressure, and heart rate on the monitor interface. As well, there should be audible tones corresponding to the heart rate and O<sub>2</sub> saturation values.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[],"psd":"2018-03-15T00:00:00-06:00","ped":"2018-04-05T01:00:00-06:00"})

**Comment by rsauvehoover** [comment]
Currently no audible tone, but observations can be made
