### ISSUE TITLE
Disable exit button for Patient on Android

### ISSUE THREAD

**Issue by kuzi117** [MockCode/MockCode#64]
We can just hit the back button instead.

**Comment by rsauvehoover** [comment]
## Summary
## Other links or relevant information
## Roadmap Data
####  🗓 Start Date: 02 - 26 - 2018
####  🗓 Expected Date: 03 - 15 - 2018
####  🏷 Label: enhancement
####  📈 Progress (0-1): 0

**Comment by rsauvehoover** [comment]
Can also just do the swipey thing on IOS.

**Comment by hughboi** [comment]
duplicate issue; already exists by #59
